/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiTrackSessionRouteImport } from './routes/api/track/session'
import { Route as ApiTrackHeadlineEventRouteImport } from './routes/api/track/headline-event'
import { Route as ApiTrackEventRouteImport } from './routes/api/track/event'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminSeedRouteImport } from './routes/api/admin/seed'
import { Route as ApiAdminQuizzesRouteImport } from './routes/api/admin/quizzes'
import { Route as ApiAdminQuizRouteImport } from './routes/api/admin/quiz'
import { Route as ApiAdminProvisionDomainRouteImport } from './routes/api/admin/provision-domain'
import { Route as ApiAdminHeadlineVariantsRouteImport } from './routes/api/admin/headline-variants'
import { Route as ApiAdminHeadlineVariantRouteImport } from './routes/api/admin/headline-variant'
import { Route as ApiAdminHeadlineStatsRouteImport } from './routes/api/admin/headline-stats'
import { Route as ApiAdminFunnelStatsRouteImport } from './routes/api/admin/funnel-stats'
import { Route as ApiAdminExtractSignalsRouteImport } from './routes/api/admin/extract-signals'
import { Route as AdminQuizzesQuizIdRouteImport } from './routes/admin/quizzes.$quizId'

const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackSessionRoute = ApiTrackSessionRouteImport.update({
  id: '/api/track/session',
  path: '/api/track/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackHeadlineEventRoute = ApiTrackHeadlineEventRouteImport.update({
  id: '/api/track/headline-event',
  path: '/api/track/headline-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackEventRoute = ApiTrackEventRouteImport.update({
  id: '/api/track/event',
  path: '/api/track/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedRoute = ApiAdminSeedRouteImport.update({
  id: '/api/admin/seed',
  path: '/api/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuizzesRoute = ApiAdminQuizzesRouteImport.update({
  id: '/api/admin/quizzes',
  path: '/api/admin/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuizRoute = ApiAdminQuizRouteImport.update({
  id: '/api/admin/quiz',
  path: '/api/admin/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProvisionDomainRoute = ApiAdminProvisionDomainRouteImport.update({
  id: '/api/admin/provision-domain',
  path: '/api/admin/provision-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHeadlineVariantsRoute =
  ApiAdminHeadlineVariantsRouteImport.update({
    id: '/api/admin/headline-variants',
    path: '/api/admin/headline-variants',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminHeadlineVariantRoute = ApiAdminHeadlineVariantRouteImport.update({
  id: '/api/admin/headline-variant',
  path: '/api/admin/headline-variant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHeadlineStatsRoute = ApiAdminHeadlineStatsRouteImport.update({
  id: '/api/admin/headline-stats',
  path: '/api/admin/headline-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFunnelStatsRoute = ApiAdminFunnelStatsRouteImport.update({
  id: '/api/admin/funnel-stats',
  path: '/api/admin/funnel-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExtractSignalsRoute = ApiAdminExtractSignalsRouteImport.update({
  id: '/api/admin/extract-signals',
  path: '/api/admin/extract-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesQuizIdRoute = AdminQuizzesQuizIdRouteImport.update({
  id: '/admin/quizzes/$quizId',
  path: '/admin/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/leads': typeof ApiLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/api/admin/extract-signals': typeof ApiAdminExtractSignalsRoute
  '/api/admin/funnel-stats': typeof ApiAdminFunnelStatsRoute
  '/api/admin/headline-stats': typeof ApiAdminHeadlineStatsRoute
  '/api/admin/headline-variant': typeof ApiAdminHeadlineVariantRoute
  '/api/admin/headline-variants': typeof ApiAdminHeadlineVariantsRoute
  '/api/admin/provision-domain': typeof ApiAdminProvisionDomainRoute
  '/api/admin/quiz': typeof ApiAdminQuizRoute
  '/api/admin/quizzes': typeof ApiAdminQuizzesRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/track/event': typeof ApiTrackEventRoute
  '/api/track/headline-event': typeof ApiTrackHeadlineEventRoute
  '/api/track/session': typeof ApiTrackSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/leads': typeof ApiLeadsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/api/admin/extract-signals': typeof ApiAdminExtractSignalsRoute
  '/api/admin/funnel-stats': typeof ApiAdminFunnelStatsRoute
  '/api/admin/headline-stats': typeof ApiAdminHeadlineStatsRoute
  '/api/admin/headline-variant': typeof ApiAdminHeadlineVariantRoute
  '/api/admin/headline-variants': typeof ApiAdminHeadlineVariantsRoute
  '/api/admin/provision-domain': typeof ApiAdminProvisionDomainRoute
  '/api/admin/quiz': typeof ApiAdminQuizRoute
  '/api/admin/quizzes': typeof ApiAdminQuizzesRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/track/event': typeof ApiTrackEventRoute
  '/api/track/headline-event': typeof ApiTrackHeadlineEventRoute
  '/api/track/session': typeof ApiTrackSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/leads': typeof ApiLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/api/admin/extract-signals': typeof ApiAdminExtractSignalsRoute
  '/api/admin/funnel-stats': typeof ApiAdminFunnelStatsRoute
  '/api/admin/headline-stats': typeof ApiAdminHeadlineStatsRoute
  '/api/admin/headline-variant': typeof ApiAdminHeadlineVariantRoute
  '/api/admin/headline-variants': typeof ApiAdminHeadlineVariantsRoute
  '/api/admin/provision-domain': typeof ApiAdminProvisionDomainRoute
  '/api/admin/quiz': typeof ApiAdminQuizRoute
  '/api/admin/quizzes': typeof ApiAdminQuizzesRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/track/event': typeof ApiTrackEventRoute
  '/api/track/headline-event': typeof ApiTrackHeadlineEventRoute
  '/api/track/session': typeof ApiTrackSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oferta'
    | '/admin/login'
    | '/api/leads'
    | '/admin/'
    | '/admin/quizzes/$quizId'
    | '/api/admin/extract-signals'
    | '/api/admin/funnel-stats'
    | '/api/admin/headline-stats'
    | '/api/admin/headline-variant'
    | '/api/admin/headline-variants'
    | '/api/admin/provision-domain'
    | '/api/admin/quiz'
    | '/api/admin/quizzes'
    | '/api/admin/seed'
    | '/api/admin/upload'
    | '/api/track/event'
    | '/api/track/headline-event'
    | '/api/track/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oferta'
    | '/admin/login'
    | '/api/leads'
    | '/admin'
    | '/admin/quizzes/$quizId'
    | '/api/admin/extract-signals'
    | '/api/admin/funnel-stats'
    | '/api/admin/headline-stats'
    | '/api/admin/headline-variant'
    | '/api/admin/headline-variants'
    | '/api/admin/provision-domain'
    | '/api/admin/quiz'
    | '/api/admin/quizzes'
    | '/api/admin/seed'
    | '/api/admin/upload'
    | '/api/track/event'
    | '/api/track/headline-event'
    | '/api/track/session'
  id:
    | '__root__'
    | '/'
    | '/oferta'
    | '/admin/login'
    | '/api/leads'
    | '/admin/'
    | '/admin/quizzes/$quizId'
    | '/api/admin/extract-signals'
    | '/api/admin/funnel-stats'
    | '/api/admin/headline-stats'
    | '/api/admin/headline-variant'
    | '/api/admin/headline-variants'
    | '/api/admin/provision-domain'
    | '/api/admin/quiz'
    | '/api/admin/quizzes'
    | '/api/admin/seed'
    | '/api/admin/upload'
    | '/api/track/event'
    | '/api/track/headline-event'
    | '/api/track/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfertaRoute: typeof OfertaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuizzesQuizIdRoute: typeof AdminQuizzesQuizIdRoute
  ApiAdminExtractSignalsRoute: typeof ApiAdminExtractSignalsRoute
  ApiAdminFunnelStatsRoute: typeof ApiAdminFunnelStatsRoute
  ApiAdminHeadlineStatsRoute: typeof ApiAdminHeadlineStatsRoute
  ApiAdminHeadlineVariantRoute: typeof ApiAdminHeadlineVariantRoute
  ApiAdminHeadlineVariantsRoute: typeof ApiAdminHeadlineVariantsRoute
  ApiAdminProvisionDomainRoute: typeof ApiAdminProvisionDomainRoute
  ApiAdminQuizRoute: typeof ApiAdminQuizRoute
  ApiAdminQuizzesRoute: typeof ApiAdminQuizzesRoute
  ApiAdminSeedRoute: typeof ApiAdminSeedRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiTrackEventRoute: typeof ApiTrackEventRoute
  ApiTrackHeadlineEventRoute: typeof ApiTrackHeadlineEventRoute
  ApiTrackSessionRoute: typeof ApiTrackSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/session': {
      id: '/api/track/session'
      path: '/api/track/session'
      fullPath: '/api/track/session'
      preLoaderRoute: typeof ApiTrackSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/headline-event': {
      id: '/api/track/headline-event'
      path: '/api/track/headline-event'
      fullPath: '/api/track/headline-event'
      preLoaderRoute: typeof ApiTrackHeadlineEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/event': {
      id: '/api/track/event'
      path: '/api/track/event'
      fullPath: '/api/track/event'
      preLoaderRoute: typeof ApiTrackEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed': {
      id: '/api/admin/seed'
      path: '/api/admin/seed'
      fullPath: '/api/admin/seed'
      preLoaderRoute: typeof ApiAdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/quizzes': {
      id: '/api/admin/quizzes'
      path: '/api/admin/quizzes'
      fullPath: '/api/admin/quizzes'
      preLoaderRoute: typeof ApiAdminQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/quiz': {
      id: '/api/admin/quiz'
      path: '/api/admin/quiz'
      fullPath: '/api/admin/quiz'
      preLoaderRoute: typeof ApiAdminQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/provision-domain': {
      id: '/api/admin/provision-domain'
      path: '/api/admin/provision-domain'
      fullPath: '/api/admin/provision-domain'
      preLoaderRoute: typeof ApiAdminProvisionDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/headline-variants': {
      id: '/api/admin/headline-variants'
      path: '/api/admin/headline-variants'
      fullPath: '/api/admin/headline-variants'
      preLoaderRoute: typeof ApiAdminHeadlineVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/headline-variant': {
      id: '/api/admin/headline-variant'
      path: '/api/admin/headline-variant'
      fullPath: '/api/admin/headline-variant'
      preLoaderRoute: typeof ApiAdminHeadlineVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/headline-stats': {
      id: '/api/admin/headline-stats'
      path: '/api/admin/headline-stats'
      fullPath: '/api/admin/headline-stats'
      preLoaderRoute: typeof ApiAdminHeadlineStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/funnel-stats': {
      id: '/api/admin/funnel-stats'
      path: '/api/admin/funnel-stats'
      fullPath: '/api/admin/funnel-stats'
      preLoaderRoute: typeof ApiAdminFunnelStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/extract-signals': {
      id: '/api/admin/extract-signals'
      path: '/api/admin/extract-signals'
      fullPath: '/api/admin/extract-signals'
      preLoaderRoute: typeof ApiAdminExtractSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes/$quizId': {
      id: '/admin/quizzes/$quizId'
      path: '/admin/quizzes/$quizId'
      fullPath: '/admin/quizzes/$quizId'
      preLoaderRoute: typeof AdminQuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfertaRoute: OfertaRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminQuizzesQuizIdRoute: AdminQuizzesQuizIdRoute,
  ApiAdminExtractSignalsRoute: ApiAdminExtractSignalsRoute,
  ApiAdminFunnelStatsRoute: ApiAdminFunnelStatsRoute,
  ApiAdminHeadlineStatsRoute: ApiAdminHeadlineStatsRoute,
  ApiAdminHeadlineVariantRoute: ApiAdminHeadlineVariantRoute,
  ApiAdminHeadlineVariantsRoute: ApiAdminHeadlineVariantsRoute,
  ApiAdminProvisionDomainRoute: ApiAdminProvisionDomainRoute,
  ApiAdminQuizRoute: ApiAdminQuizRoute,
  ApiAdminQuizzesRoute: ApiAdminQuizzesRoute,
  ApiAdminSeedRoute: ApiAdminSeedRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiTrackEventRoute: ApiTrackEventRoute,
  ApiTrackHeadlineEventRoute: ApiTrackHeadlineEventRoute,
  ApiTrackSessionRoute: ApiTrackSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
