/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminSeedRouteImport } from './routes/api/admin/seed'
import { Route as ApiAdminQuizzesRouteImport } from './routes/api/admin/quizzes'
import { Route as ApiAdminQuizRouteImport } from './routes/api/admin/quiz'
import { Route as ApiAdminProvisionDomainRouteImport } from './routes/api/admin/provision-domain'
import { Route as AdminQuizzesQuizIdRouteImport } from './routes/admin/quizzes.$quizId'

const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedRoute = ApiAdminSeedRouteImport.update({
  id: '/api/admin/seed',
  path: '/api/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuizzesRoute = ApiAdminQuizzesRouteImport.update({
  id: '/api/admin/quizzes',
  path: '/api/admin/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuizRoute = ApiAdminQuizRouteImport.update({
  id: '/api/admin/quiz',
  path: '/api/admin/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProvisionDomainRoute = ApiAdminProvisionDomainRouteImport.update({
  id: '/api/admin/provision-domain',
  path: '/api/admin/provision-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesQuizIdRoute = AdminQuizzesQuizIdRouteImport.update({
  id: '/admin/quizzes/$quizId',
  path: '/admin/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/leads': typeof ApiLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/api/admin/provision-domain': typeof ApiAdminProvisionDomainRoute
  '/api/admin/quiz': typeof ApiAdminQuizRoute
  '/api/admin/quizzes': typeof ApiAdminQuizzesRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/leads': typeof ApiLeadsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/api/admin/provision-domain': typeof ApiAdminProvisionDomainRoute
  '/api/admin/quiz': typeof ApiAdminQuizRoute
  '/api/admin/quizzes': typeof ApiAdminQuizzesRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/leads': typeof ApiLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/api/admin/provision-domain': typeof ApiAdminProvisionDomainRoute
  '/api/admin/quiz': typeof ApiAdminQuizRoute
  '/api/admin/quizzes': typeof ApiAdminQuizzesRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oferta'
    | '/admin/login'
    | '/api/leads'
    | '/admin/'
    | '/admin/quizzes/$quizId'
    | '/api/admin/provision-domain'
    | '/api/admin/quiz'
    | '/api/admin/quizzes'
    | '/api/admin/seed'
    | '/api/admin/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oferta'
    | '/admin/login'
    | '/api/leads'
    | '/admin'
    | '/admin/quizzes/$quizId'
    | '/api/admin/provision-domain'
    | '/api/admin/quiz'
    | '/api/admin/quizzes'
    | '/api/admin/seed'
    | '/api/admin/upload'
  id:
    | '__root__'
    | '/'
    | '/oferta'
    | '/admin/login'
    | '/api/leads'
    | '/admin/'
    | '/admin/quizzes/$quizId'
    | '/api/admin/provision-domain'
    | '/api/admin/quiz'
    | '/api/admin/quizzes'
    | '/api/admin/seed'
    | '/api/admin/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfertaRoute: typeof OfertaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuizzesQuizIdRoute: typeof AdminQuizzesQuizIdRoute
  ApiAdminProvisionDomainRoute: typeof ApiAdminProvisionDomainRoute
  ApiAdminQuizRoute: typeof ApiAdminQuizRoute
  ApiAdminQuizzesRoute: typeof ApiAdminQuizzesRoute
  ApiAdminSeedRoute: typeof ApiAdminSeedRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed': {
      id: '/api/admin/seed'
      path: '/api/admin/seed'
      fullPath: '/api/admin/seed'
      preLoaderRoute: typeof ApiAdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/quizzes': {
      id: '/api/admin/quizzes'
      path: '/api/admin/quizzes'
      fullPath: '/api/admin/quizzes'
      preLoaderRoute: typeof ApiAdminQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/quiz': {
      id: '/api/admin/quiz'
      path: '/api/admin/quiz'
      fullPath: '/api/admin/quiz'
      preLoaderRoute: typeof ApiAdminQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/provision-domain': {
      id: '/api/admin/provision-domain'
      path: '/api/admin/provision-domain'
      fullPath: '/api/admin/provision-domain'
      preLoaderRoute: typeof ApiAdminProvisionDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes/$quizId': {
      id: '/admin/quizzes/$quizId'
      path: '/admin/quizzes/$quizId'
      fullPath: '/admin/quizzes/$quizId'
      preLoaderRoute: typeof AdminQuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfertaRoute: OfertaRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminQuizzesQuizIdRoute: AdminQuizzesQuizIdRoute,
  ApiAdminProvisionDomainRoute: ApiAdminProvisionDomainRoute,
  ApiAdminQuizRoute: ApiAdminQuizRoute,
  ApiAdminQuizzesRoute: ApiAdminQuizzesRoute,
  ApiAdminSeedRoute: ApiAdminSeedRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
